language: cpp

sudo: false

compiler: clang

addons:
  apt:
    update: true
    sources:  [ 'george-edison55-precise-backports' ]
    packages: [ 'cmake', 'cmake-data' ]

matrix:
  exclude:
    - os: linux
  include:
    - os: osx
      osx_image: xcode9.3
      env: MASON_PLATFORM=osx
    - os: linux
      dist: trusty
      env: MASON_PLATFORM=linux

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}

after_success:
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
